service: serverless-policy
provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "sns:*"

custom:
  monitorSnsTopic: "monitorTopic"
  monitorSnsTopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:custom.monitorSnsTopic}"
  consumerSnsTopic: "consumerTopic"
  consumerSnsTopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:custom.consumerSnsTopic}"

functions:
  producer:
    handler: src/handler.producer
    environment:
      monitorSnsTopicArn: ${self:custom.monitorSnsTopicArn}
  consumer:
    handler: src/handler.consumer
    events:
    - sns: ${self:custom.consumerSnsTopic}    
  monitor:
    handler: src/handler.monitor
    events:
    - sns: ${self:custom.monitorSnsTopic}
    environment:
      consumerSnsTopicArn: ${self:custom.consumerSnsTopicArn}

# plugins:
#   - serverless-offline-sns
#   - serverless-offline
