service: serverless-policy
provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "sns:*"

custom:
  monitorSnsTopic: "monitorTopic"
  monitorSnsTopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:custom.monitorSnsTopic}"
  consumerSnsTopic: "consumerTopic"
  consumerSnsTopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:custom.consumerSnsTopic}"
  intermediateSnsTopic: "intermediateTopic"
  intermediateSnsTopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${self:custom.intermediateSnsTopic}"

functions:
  producer:
    handler: src/handler.producer
    environment:
      monitorSnsTopicArn: ${self:custom.monitorSnsTopicArn}
      intermediateSnsTopicArn: ${self:custom.intermediateSnsTopicArn}
      consumerSnsTopicArn: ${self:custom.consumerSnsTopicArn}
  consumer:
    handler: src/handler.consumer
    events:
    - sns: ${self:custom.consumerSnsTopic}
  intermediate:
    handler: src/handler.intermediate
    events:
    - sns: ${self:custom.intermediateSnsTopic}  
    environment:
      monitorSnsTopicArn: ${self:custom.monitorSnsTopicArn}
      intermediateSnsTopicArn: ${self:custom.intermediateSnsTopicArn}
      consumerSnsTopicArn: ${self:custom.consumerSnsTopicArn}
  monitor:
    handler: src/handler.monitor
    events:
    - sns: ${self:custom.monitorSnsTopic}
    environment:
      intermediateSnsTopicArn: ${self:custom.intermediateSnsTopicArn}
      consumerSnsTopicArn: ${self:custom.consumerSnsTopicArn}

# plugins:
#   - serverless-offline-sns
#   - serverless-offline
